### ISSUE TITLE
problems with sending long SMS

### ISSUE THREAD

**Issue by niki91** [python-smpplib/python-smpplib#74] opened 2018-12-18 11:24 UTC
Hello. in the library there are problems with sending long SMS

**Comment by eigenein** [comment] 2018-12-18 12:44
Hello, we need more details. Could you elaborate?

**Comment by niki91** [comment] 2018-12-18 14:15
Tested on goip (gateway). Cyrillic and Latin are not sent. there is a feeling that the formation of the PDU is not correct. Cyrillic text length 140 characters when sending long text.

**Comment by eigenein** [comment] 2018-12-18 14:17
That works fine for me at the moment. Any minimal reproducible example?

**Comment by niki91** [comment] 2018-12-18 14:20
89525215000 Привет. Мир
b'\x00\x00\x00M\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x0089226970000\x00\x01\x0089525215000\x00\x00\x00\x00\x00\x00\x01\x00\x08\x00\x16\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@'

89525215000 Привет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет.
b'\x00\x00\x00\xc3\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x0089226970000\x00\x01\x0089525215000\x00@\x00\x00\x00\x00\x01\x00\x08\x00\x8c\x05\x00\x03z\x02\x01\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f'

b'\x00\x00\x00\xa1\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x03\x00\x01\x0089226970000\x00\x01\x0089525215000\x00@\x00\x00\x00\x00\x01\x00\x08\x00j\x05\x00\x03z\x02\x02\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.'

**Comment by eigenein** [comment] 2018-12-19 00:08
What's wrong with the first example? Looks like you posted the entire PDU, but its size is something different.

```python
In [2]: from smpplib import consts, gsm

In [3]: parts, data_coding, esm_class = gsm.make_parts('Привет. Мир')

In [4]: parts
Out[4]: [b'\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@']

In [7]: data_coding == consts.SMPP_ENCODING_ISO10646
Out[7]: True

In [8]: esm_class == consts.SMPP_MSGTYPE_DEFAULT
Out[8]: True
```

**Comment by niki91** [comment] 2018-12-19 05:37
The first example is a short message, it works fine.
Problems arise when the message is long: second example

Got the dump in:

def send_pdu(self, p):
        """Send PDU to the SMSC"""
...
        print(generated)
...

**Comment by eigenein** [comment] 2018-12-19 16:48
Just tested it as well, the message has been successfully received on a device:

```python
from smpplib import consts, gsm
from smpplib.client import Client


parts, data_coding, esm_class = gsm.make_parts('Привет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет. МирПривет.')

with Client('localhost', 1234) as client:
    client.connect()
    client.bind_transmitter(system_id='X', password='X')
    for part in parts:
        client.send_message(
            source_addr_ton=consts.SMPP_TON_ALNUM,
            source_addr_npi=consts.SMPP_NPI_UNK,
            source_addr='XXXX',
            dest_addr_ton=consts.SMPP_TON_INTL,
            dest_addr_npi=consts.SMPP_NPI_ISDN,
            destination_addr='316XXXXXXXX',
            short_message=part,
            data_coding=data_coding,
            esm_class=esm_class,
            registered_delivery=consts.SMPP_SMSC_DELIVERY_RECEIPT_BOTH,
        )
        client.read_pdu()
```

```python
In [3]: len(parts)
Out[3]: 2

In [4]: len(parts[0]), len(parts[1])
Out[4]: (140, 106)

In [5]: parts[0]
Out[5]: b'\x05\x00\x03>\x02\x01\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f'

In [6]: parts[1]
Out[6]: b'\x05\x00\x03>\x02\x02\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.\x00 \x04\x1c\x048\x04@\x04\x1f\x04@\x048\x042\x045\x04B\x00.'
```

**Comment by niki91** [comment] 2018-12-24 11:35
Hello.
Can you throw off the full pdu?

**Comment by SuperMasterBlasterLaser** [comment] 2019-01-12 08:45
I think this is connected to my own issue #53

**Comment by eigenein** [comment] 2019-01-15 18:49
Sorry for the late reply. I could throw the full PDU, but indeed our parts are different. Are you using the latest package version? As @SuperMasterBlasterLaser mentioned, we fixed the bug a few months ago which could lead to a message being improperly encoded.

**Comment by niki91** [comment] 2019-01-16 18:36
Date files smpplib the end of November. master

**Comment by niki91** [comment] 2019-01-21 17:55
Contacted those GOIP support. The gateway comes in is one part of the message which goes to the phone. it is not know what and where to check.=(

**Comment by eigenein** [comment] 2019-01-22 19:57
Well, we still have one thing to check. You said we got different `parts` and the code is more or less fresh. Which is weird, so let's try like that. Could you give us your specific commit hash and a piece of code that gives you the result different from [mine](https://github.com/python-smpplib/python-smpplib/issues/74#issuecomment-448664633)?

Then I'll check it out and try to reproduce.

As a side note: please do check if your `esm_class` is `consts.SMPP_GSMFEAT_UDHI`.

**Comment by niki91** [comment] 2019-01-23 17:23
"Well, we still have one thing to check....."
I found the difference. It is due to the fact that there generiruyutsya message number(if not mistaken)The problem is not here.

**Comment by eigenein** [comment] 2019-02-06 13:47
We're talking in private a lot, debugging PDUs. For now looks like it was an inconsistent gateway behaviour. We'll close this once confirmed.

**Comment by niki91** [comment] 2019-02-06 14:26
> We're talking in private a lot, debugging PDUs. For now looks like it was an inconsistent gateway behaviour. We'll close this once confirmed.

+ For gateway GOIP use method smpp message_payload.

**Comment by eigenein** [comment] 2019-02-18 12:57
Hi @niki91,

Is it still working fine? Could the issue be closed?

**Comment by eigenein** [comment] 2019-03-01 15:15
Closed by agreement with @niki91.

**Closed by eigenein** 2019-03-01 15:15 UTC
