### ISSUE TITLE
Support for Multiple Recipients

### ISSUE THREAD

**Issue by borsn** [python-smpplib/python-smpplib#96] opened 2019-08-26 19:18 UTC
SMPP supports multiple recipients.

Does smpplib support it?

And how do I implement it?

**Comment by eigenein** [comment] 2019-08-26 20:33
Duplicate of https://github.com/python-smpplib/python-smpplib/issues/80

**Closed by eigenein** 2019-08-26 20:33 UTC
Labels: duplicate

**Comment by Lynesth** [comment] 2019-09-07 05:27
@borsn I would just like to add that even though it is supported by SMPP, there's like no SMPP provider actually supporting the `SUBMIT_MULTI` operation. If you found one, I am interested (and will add the feature to python-smpplib).
